# defaults for every server
user    = ansible
port    = 22
keyPath = ~/.ssh/pk

[sshbox1]
ip   = 127.0.0.1
user = root
port = 32773

[sshbox2]
ip   = 127.0.0.1
user = root
port = 32774

[sshbox3]
ip   = 127.0.0.1
user = root
port = 32775

[sshbox4]
ip   = 127.0.0.1
user = root
port = 32776

[sshbox5]
ip   = 127.0.0.1
user = root
port = 32777
